AWSTemplateFormatVersion: "2010-09-09"
Description: tmp

Resources:
  AlertSNSTopic:
    Type: AWS::SNS::Topic

  OpenSackFlowSNSTopic:
    Type: AWS::SNS::Topic

  MakeCoffeeFlowSNSTopic:
    Type: AWS::SNS::Topic

  ReactionFlowSNSTopic:
    Type: AWS::SNS::Topic
    
  ShowMakeTimesSNSTopic:
    Type: AWS::SNS::Topic

  DataStoreTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: partitionId
          AttributeType: S
        - AttributeName: sortId
          AttributeType: S
      KeySchema:
        - AttributeName: partitionId
          KeyType: HASH
        - AttributeName: sortId
          KeyType: RANGE

Outputs:
  AlertSNSTopicArn:
    Value: !Ref AlertSNSTopic

  OpenSackFlowSNSTopicArn:
    Value: !Ref OpenSackFlowSNSTopic

  MakeCoffeeFlowSNSTopicArn:
    Value: !Ref MakeCoffeeFlowSNSTopic

  ReactionFlowSNSTopicArn:
    Value: !Ref ReactionFlowSNSTopic

  ShowMakeTimesSNSTopicArn:
    Value: !Ref ShowMakeTimesSNSTopic

  DataStoreTableName:
    Value: !Ref DataStoreTable
