Transform: AWS::Serverless-2016-10-31
Parameters:
  Env:
    Type: String

  LoggerLayerArn:
    Type: String

  AlertSnsTopicArn:
    Type: String

  ShowMakeTimesSnsTopicArn:
    Type: String

Globals:
  Function:
    Handler: index.handler
    Runtime: python3.7
    Timeout: 150
    MemorySize: 256
    AutoPublishAlias: !Ref Env
    Layers:
      - !Ref LoggerLayerArn

Resources:
  MonthlyShowUserMakeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: monthly_show_user_make
      Policies:
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
      Environment:
        Variables:
          TARGET_TOPIC_ARN: !Ref ShowMakeTimesSnsTopicArn
      Events:
        Monthly:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: cron(30 2 1 * ? *)
