AWSTemplateFormatVersion: "2010-09-09"
Description: tmp

Parameters:
  Env:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /FukuokaDeLongiBot/Application/Env

  TargetChannelId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /FukuokaDeLongiBot/Application/TargetChannelId

  LoggerLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /FukuokaDeLongiBot/Layer/LoggerLayerArn

  SlackClientLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /FukuokaDeLongiBot/Layer/SlackClientLayerArn

Resources:
  ResourcesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/resources/template.yml

  ButtonFunctionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/button_function/sam.yml
      Parameters:
        Env: !Ref Env
        LoggerLayerArn: !Ref LoggerLayerArn
        AlertSnsTopicArn: !GetAtt ResourcesStack.Outputs.AlertSNSTopicArn
        OpenSackFlowSNSTopicArn: !GetAtt ResourcesStack.Outputs.OpenSackFlowSNSTopicArn
        MakeCoffeeFlowSNSTopicArn: !GetAtt ResourcesStack.Outputs.MakeCoffeeFlowSNSTopicArn

  MakeCoffeeFlowStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/make_coffee_flow/sam.yml
      Parameters:
        Env: !Ref Env
        LoggerLayerArn: !Ref LoggerLayerArn
        SlackClientLayerArn: !Ref SlackClientLayerArn
        AlertSnsTopicArn: !GetAtt ResourcesStack.Outputs.AlertSNSTopicArn
        MakeCoffeeFlowSNSTopicArn: !GetAtt ResourcesStack.Outputs.MakeCoffeeFlowSNSTopicArn
        DataStoreTableName: !GetAtt ResourcesStack.Outputs.DataStoreTableName

  OpenSackFlowStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/open_sack_flow/sam.yml
      Parameters:
        Env: !Ref Env
        LoggerLayerArn: !Ref LoggerLayerArn
        SlackClientLayerArn: !Ref SlackClientLayerArn
        AlertSnsTopicArn: !GetAtt ResourcesStack.Outputs.AlertSNSTopicArn
        OpenSackFlowSNSTopicArn: !GetAtt ResourcesStack.Outputs.OpenSackFlowSNSTopicArn
        DataStoreTableName: !GetAtt ResourcesStack.Outputs.DataStoreTableName

  HookApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/hook_api/sam.yml
      Parameters:
        Env: !Ref Env
        LoggerLayerArn: !Ref LoggerLayerArn
        AlertSnsTopicArn: !GetAtt ResourcesStack.Outputs.AlertSNSTopicArn
        ReactionFlowSnsTopicArn: !GetAtt ResourcesStack.Outputs.ReactionFlowSNSTopicArn

  ReactionFlowStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/reaction_flow/sam.yml
      Parameters:
        Env: !Ref Env
        LoggerLayerArn: !Ref LoggerLayerArn
        SlackClientLayerArn: !Ref SlackClientLayerArn
        AlertSnsTopicArn: !GetAtt ResourcesStack.Outputs.AlertSNSTopicArn
        ReactionFlowSNSTopicArn: !GetAtt ResourcesStack.Outputs.ReactionFlowSNSTopicArn
        DataStoreTableName: !GetAtt ResourcesStack.Outputs.DataStoreTableName

  ShowMakeTimesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/show_make_times/sam.yml
      Parameters:
        Env: !Ref Env
        LoggerLayerArn: !Ref LoggerLayerArn
        SlackClientLayerArn: !Ref SlackClientLayerArn
        AlertSnsTopicArn: !GetAtt ResourcesStack.Outputs.AlertSNSTopicArn
        ShowMakeTimesSnsTopicArn: !GetAtt ResourcesStack.Outputs.ShowMakeTimesSNSTopicArn
        DataStoreTableName: !GetAtt ResourcesStack.Outputs.DataStoreTableName

  CronFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/cron_functions/sam.yml
      Parameters:
        Env: !Ref Env
        LoggerLayerArn: !Ref LoggerLayerArn
        AlertSnsTopicArn: !GetAtt ResourcesStack.Outputs.AlertSNSTopicArn
        ShowMakeTimesSnsTopicArn: !GetAtt ResourcesStack.Outputs.ShowMakeTimesSNSTopicArn

Outputs:
  AlertSNSTopicArn:
    Value: !GetAtt ResourcesStack.Outputs.AlertSNSTopicArn

  IoTButtonFunctionName:
    Value: !GetAtt ButtonFunctionStack.Outputs.IoTButtonFunctionName

  ReactionHookApiUrl:
    Value: !GetAtt HookApiStack.Outputs.ReactionHookUrl
