Transform: AWS::Serverless-2016-10-31
Parameters:
  Env:
    Type: String

  LoggerLayerArn:
    Type: String

  SlackClientLayerArn:
    Type: String

  AlertSnsTopicArn:
    Type: String

  ReactionFlowSNSTopicArn:
    Type: String

  DataStoreTableName:
    Type: String

Globals:
  Function:
    Handler: index.handler
    Runtime: python3.7
    Timeout: 150
    MemorySize: 256
    AutoPublishAlias: !Ref Env
    Layers:
      - !Ref LoggerLayerArn

Resources:
  FirstUpdateMakeHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 1st_update_make_history
      Policies:
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource:
                - "*"
      Environment:
        Variables:
          DATA_STORE_TABLE_NAME: !Ref DataStoreTableName
      Layers:
        - !Ref SlackClientLayerArn
      Events:
        SNSTrigger:
          Type: SNS
          Properties:
            Topic: !Ref ReactionFlowSNSTopicArn
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Destination: !Ref SecondUpsertUserMakeHistoryFunction.Alias
            Type: Lambda

  FirstUpdateMakeHistoryLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../log_group.yml
      Parameters:
        FunctionName: !Ref FirstUpdateMakeHistoryFunction
        AlartSnsTopicArn: !Ref AlertSnsTopicArn

  SecondUpsertUserMakeHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 2nd_upsert_user_make_history
      Policies:
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DATA_STORE_TABLE_NAME: !Ref DataStoreTableName
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Destination: !Ref ThirdUpdateSlackMessageFunction.Alias
            Type: Lambda

  SecondUpsertUserMakeHistoryLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../log_group.yml
      Parameters:
        FunctionName: !Ref SecondUpsertUserMakeHistoryFunction
        AlartSnsTopicArn: !Ref AlertSnsTopicArn

  ThirdUpdateSlackMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 3rd_update_slack_message
      Policies:
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource:
                - "*"
      Layers:
        - !Ref SlackClientLayerArn

  ThirdUpdateSlackMessageLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../log_group.yml
      Parameters:
        FunctionName: !Ref ThirdUpdateSlackMessageFunction
        AlartSnsTopicArn: !Ref AlertSnsTopicArn
