AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String

  LoggerLayerArn:
    Type: String

  SlackClientLayerArn:
    Type: String

  AlertSnsTopicArn:
    Type: String

  OpenSackFlowSNSTopicArn:
    Type: String

  DataStoreTableName:
    Type: String

Globals:
  Function:
    Handler: index.handler
    Runtime: python3.7
    Timeout: 150
    MemorySize: 256
    AutoPublishAlias: !Ref Env
    Layers:
      - !Ref LoggerLayerArn

Resources:
  FirstSendMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 1st_send_message
      Policies:
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource:
                - "*"
      Environment:
        Variables:
          DATA_STORE_TABLE_NAME: !Ref DataStoreTableName
      Layers:
        - !Ref SlackClientLayerArn
      Events:
        SNSTrigger:
          Type: SNS
          Properties:
            Topic: !Ref OpenSackFlowSNSTopicArn
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Destination: !Ref SecondResetSackCounterFunction.Alias
            Type: Lambda

  FirstSendMessageLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../log_group.yml
      Parameters:
        FunctionName: !Ref FirstSendMessageFunction
        AlartSnsTopicArn: !Ref AlertSnsTopicArn

  SecondResetSackCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 2nd_reset_sack_counter
      Policies:
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DATA_STORE_TABLE_NAME: !Ref DataStoreTableName
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Destination: !Ref ThirdInsertSackHistoryFunction.Alias
            Type: Lambda

  SecondResetSackCounterLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../log_group.yml
      Parameters:
        FunctionName: !Ref SecondResetSackCounterFunction
        AlartSnsTopicArn: !Ref AlertSnsTopicArn

  ThirdInsertSackHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 3rd_insert_sack_history
      Policies:
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DATA_STORE_TABLE_NAME: !Ref DataStoreTableName

  ThirdInsertSackHistoryLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../log_group.yml
      Parameters:
        FunctionName: !Ref ThirdInsertSackHistoryFunction
        AlartSnsTopicArn: !Ref AlertSnsTopicArn

  ForthSendSackHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 4th_send_sack_history
      Policies:
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource:
                - "*"
      Layers:
        - !Ref SlackClientLayerArn
      Environment:
        Variables:
          DATA_STORE_TABLE_NAME: !Ref DataStoreTableName

  ForthSendSackHistoryLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../log_group.yml
      Parameters:
        FunctionName: !Ref ForthSendSackHistoryFunction
        AlartSnsTopicArn: !Ref AlertSnsTopicArn
