AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String

  LoggerLayerArn:
    Type: String

  SlackClientLayerArn:
    Type: String

  AlertSnsTopicArn:
    Type: String

  OpenSackFlowSNSTopicArn:
    Type: String

Globals:
  Function:
    Handler: index.handler
    Runtime: python3.7
    Timeout: 150
    MemorySize: 256
    AutoPublishAlias: !Ref Env
    Layers:
      - !Ref LoggerLayerArn

Resources:
  FirstSendMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 1st_send_message
      Policies:
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource:
                - "*"
      Layers:
        - !Ref SlackClientLayerArn
      Events:
        SNSTrigger:
          Type: SNS
          Properties:
            Topic: !Ref OpenSackFlowSNSTopicArn


  FirstSendMessageLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../log_group.yml
      Parameters:
        FunctionName: !Ref FirstSendMessageFunction
        AlartSnsTopicArn: !Ref AlertSnsTopicArn
