AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String

  LoggerLayerArn:
    Type: String

  AlertSnsTopicArn:
    Type: String

Resources:
  IoTButtonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: index.handler
      Runtime: python3.7
      Timeout: 30
      MemorySize: 256
      Policies:
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
      AutoPublishAlias: !Ref Env
      Layers:
        - !Ref LoggerLayerArn

  IoTButtonLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../log_group.yml
      Parameters:
        FunctionName: !Ref IoTButtonFunction
        AlartSnsTopicArn: !Ref AlertSnsTopicArn

Outputs:
  IoTButtonFunctionName:
    Value: !Ref IoTButtonFunction
